### ISSUE TITLE
"simple-http-server:micro" container fails to start

### ISSUE THREAD

**Issue by skraft-redhat** [openshift-examples/web#20]
Hello! 

When trying to use the "simple-http-server:micro" image, the start fails with the error message: 

runc create failed: unable to start container process: exec: \"socat\": executable file not found in $PATH

**Comment by rbo** [comment]
```
 podman run -ti --rm quay.io/openshift-examples/simple-http-server:micro
Error: crun: executable file `socat` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
```
Ups

**Comment by rbo** [comment]
Image update - and works as expected.
